- hosts: all
  become: true
  vars:
    default_user: demo
  roles:
    - role: common
      vars:
        username: "{{ default_user }}"
      
    - role: security
      vars:
        regular_user: "{{ default_user }}"
        firewall_ports:
          - port: "{{ lookup('env', 'DOCKER_HOST_PORT') if lookup('env', 'APP_ENV') == 'docker' else lookup('env', 'APP_NODEPORT') }}"
            protocol: tcp
            rule: allow
      
    - role: docker

    - role: k3s
      vars:
        k3s_owner: "{{ default_user }}"
      when: lookup('env', 'APP_ENV') == "k3s"

    - role: app
      vars:
        app_owner: "{{ default_user }}"
        app_image_name: "{{ lookup('env', 'IMAGE_NAME') }}"
        app_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
        app_use_ssl: false
        app_env: "{{ lookup('env', 'APP_ENV') }}"
        app_addr: "{{ lookup('env', 'DEMO_APP_ADDR') }}"
        app_nodeport: "{{ lookup('env', 'APP_NODEPORT') }}"

          