- hosts: all
  become: true
  vars:
    default_user: demo
  roles:
    - role: common
      vars:
        username: "{{ default_user }}"
    - role: security
      vars:
        firewall_ports:
          - port: "{{ lookup('env', 'DOCKER_HOST_PORT') }}"
            protocol: tcp
            rule: allow
    - role: docker
    - role: app
      vars:
        app_owner: "{{ default_user }}"
        app_image_name: "{{ lookup('env', 'IMAGE_NAME') }}"
        app_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
        app_use_ssl: false

          