- hosts: all
  become: true
  vars:
    default_user: demo
  roles:
    - role: common
      vars:
        username: "{{ default_user }}"
      
    - role: security
      vars:
        regular_user: "{{ default_user }}"
        firewall_ports:
          - port: "{{ lookup('env', 'DOCKER_HOST_PORT') if lookup('env', 'APP_ENV') == 'docker' else lookup('env', 'APP_NODEPORT') }}"
            protocol: tcp
            rule: allow
          - port: "3000" # Grafana
            protocol: tcp
            rule: allow
          - port: "9090" # Prometheus
            protocol: tcp
            rule: allow
      
    - role: docker

    - role: k3s
      vars:
        k3s_owner: "{{ default_user }}"
      when: lookup('env', 'APP_ENV') == "k3s"

    - role: app
      vars:
        app_owner: "{{ default_user }}"
        app_use_ssl: false
        app_env: "{{ lookup('env', 'APP_ENV') }}"
        app_nodeport: "{{ lookup('env', 'APP_NODEPORT') }}"
        app_nginx_host_port: "{{ lookup('env', 'DOCKER_HOST_PORT') }}"

          