app_image_name: ops-task
app_image_tag: latest
app_bin: demo.bin
app_version: 1.0.0

app_working_dir: /etc/demo-ops
app_files_dir: /vagrant

app_owner: demo

app_files_to_copy:
  - docker-compose.yml
  - nginx.conf.template
  - .env
