---
apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    url: http://prometheus:9090
    password:
    user:
    database:
    version: 1
    editable: true