{
 "title": "App Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=\"redis_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis_exporter\"}"
    }
   ]
  },
  {
   "title": "Redis Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"redis_exporter\"}[5m])",
     "legendFormat": "{{ input }} input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"redis_exporter\"}[5m])",
     "legendFormat": "{{ output }} output"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis_exporter\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{job=\"redis_exporter\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}