- name: Create working directory
  ansible.builtin.file:
    path: "{{ app_working_dir }}"
    state: directory
    recurse: yes
    owner: "{{ app_owner }}"
    group: "{{ app_owner }}"

- name: Copy files to server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ app_working_dir }}"
  loop: "{{ app_files_to_copy }}"

- name: Get UID of the app owner
  ansible.builtin.command: id -u
  register: app_owner_id
  become_user: "{{ app_owner }}"

- name: Copy docker-compose file
  vars:
    docker_uid: "{{ app_owner_id.stdout }}"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ app_working_dir }}/docker-compose.yml"
  when: app_env == 'docker'

- name: Copy prometheus file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ app_working_dir }}/prometheus.yml"
  when: app_env == 'docker'

- name: Build docker image
  community.docker.docker_image:
    build:
      args:
        BIN: "{{ app_bin }}"
        VERSION: "{{ app_version }}"
      path: "{{ app_files_dir }}"
    name: "{{ app_image_name }}"
    tag: "{{ app_image_tag }}"
    source: build

- name: Generate CSR
  ansible.builtin.command: openssl req -new -subj "/C=IN/ST=Delhi/CN=localhost" -newkey rsa:4096 -nodes -keyout server.key -out server.csr
  args:
    chdir: "{{ app_working_dir }}"
    creates: server.csr
  when: app_use_ssl and app_env == "docker"
  become_user: "{{ app_owner }}"

- name: Generate ssl certificates
  ansible.builtin.command: openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
  args:
    chdir: "{{ app_working_dir }}"
    creates: server.crt
  when: app_use_ssl and app_env == "docker"
  become_user: "{{ app_owner }}"

- name: Copy NGINX config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ app_working_dir }}/nginx.conf"
  when: app_env == 'docker'

- name: Stop docker-compose
  community.docker.docker_compose:
    project_src: "{{ app_working_dir }}"
    state: absent
  become_user: "{{ app_owner }}"
  when: app_env == 'docker'

- name: Start docker-compose
  community.docker.docker_compose:
    project_src: "{{ app_working_dir }}"
    state: present
  become_user: "{{ app_owner }}"
  when: app_env == 'docker'

- name: Copy k3s deployment file
  ansible.builtin.template:
    src: k3s-deployment.yml.j2
    dest: "{{ app_working_dir }}/k3s-deployment.yml"
  when: app_env == 'k3s'

- name: Deploy to k3s
  ansible.builtin.command: kubectl --kubeconfig {{ k3s_kubeconfig }} apply -f k3s-deployment.yml
  args:
    chdir: "{{ app_working_dir }}"
  when: app_env == 'k3s'
  become_user: "{{ app_owner }}"