- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: restarted